//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace BIC.ETL.SqlServer.DataLayer
{
    /// <summary>
    /// Database       : BIC
    /// Data Source    : STAN-PC
    /// Server Version : 11.00.3128
    /// </summary>
    public partial class BICDB : LinqToDB.Data.DataConnection
    {
        public ITable<BalanceSheetQuarterly> BalanceSheetQuarterlies { get { return this.GetTable<BalanceSheetQuarterly>(); } }
        public ITable<CashFlowQuarterly> CashFlowQuarterlies { get { return this.GetTable<CashFlowQuarterly>(); } }
        public ITable<IncomeStatementQuarterly> IncomeStatementQuarterlies { get { return this.GetTable<IncomeStatementQuarterly>(); } }
        public ITable<Industry> Industries { get { return this.GetTable<Industry>(); } }
        public ITable<KeyRatio> KeyRatios { get { return this.GetTable<KeyRatio>(); } }
        public ITable<Sector> Sectors { get { return this.GetTable<Sector>(); } }
        public ITable<Security> Securities { get { return this.GetTable<Security>(); } }
        public ITable<TimeDimmension> TimeDimmensions { get { return this.GetTable<TimeDimmension>(); } }

        public BICDB()
        {
            InitDataContext();
            InitMappingSchema();
        }

        public BICDB(string configuration)
            : base(configuration)
        {
            InitDataContext();
            InitMappingSchema();
        }

        public BICDB(LinqToDbConnectionOptions options)
            : base(options)
        {
            InitDataContext();
            InitMappingSchema();
        }

        partial void InitDataContext();
        partial void InitMappingSchema();
    }

    [Table(Schema = "dbo", Name = "BalanceSheetQuarterly")]
    public partial class BalanceSheetQuarterly
    {
        [Column(), PrimaryKey(1), NotNull] public int SecurityID { get; set; } // int
        [Column(), PrimaryKey(2), NotNull] public int Year { get; set; } // int
        [Column(), PrimaryKey(3), NotNull] public int Quarter { get; set; } // int
        [Column("endDate"), NotNull] public DateTime EndDate { get; set; } // date
        [Column("cash"), Nullable] public decimal? Cash { get; set; } // decimal(38, 0)
        [Column("intangibleAssets"), Nullable] public decimal? IntangibleAssets { get; set; } // decimal(38, 0)
        [Column("otherCurrentAssets"), Nullable] public decimal? OtherCurrentAssets { get; set; } // decimal(38, 0)
        [Column("totalCurrentAssets"), Nullable] public decimal? TotalCurrentAssets { get; set; } // decimal(38, 0)
        [Column("goodWill"), Nullable] public decimal? GoodWill { get; set; } // decimal(38, 0)
        [Column("retainedEarnings"), Nullable] public decimal? RetainedEarnings { get; set; } // decimal(38, 0)
        [Column("propertyPlantEquipment"), Nullable] public decimal? PropertyPlantEquipment { get; set; } // decimal(38, 0)
        [Column("longTermInvestments"), Nullable] public decimal? LongTermInvestments { get; set; } // decimal(38, 0)
        [Column("shortTermInvestments"), Nullable] public decimal? ShortTermInvestments { get; set; } // decimal(38, 0)
        [Column("netReceivables"), Nullable] public decimal? NetReceivables { get; set; } // decimal(38, 0)
        [Column("inventory"), Nullable] public decimal? Inventory { get; set; } // decimal(38, 0)
        [Column("accountsPayable"), Nullable] public decimal? AccountsPayable { get; set; } // decimal(38, 0)
        [Column("otherAssets"), Nullable] public decimal? OtherAssets { get; set; } // decimal(38, 0)
        [Column("totalAssets"), Nullable] public decimal? TotalAssets { get; set; } // decimal(38, 0)
        [Column("otherCurrentLiab"), Nullable] public decimal? OtherCurrentLiab { get; set; } // decimal(38, 0)
        [Column("totalCurrentLiabilities"), Nullable] public decimal? TotalCurrentLiabilities { get; set; } // decimal(38, 0)
        [Column("shortLongTermDebt"), Nullable] public decimal? ShortLongTermDebt { get; set; } // decimal(38, 0)
        [Column("otherLiab"), Nullable] public decimal? OtherLiab { get; set; } // decimal(38, 0)
        [Column("longTermDebt"), Nullable] public decimal? LongTermDebt { get; set; } // decimal(38, 0)
        [Column("totalLiab"), Nullable] public decimal? TotalLiab { get; set; } // decimal(38, 0)
        [Column("netTangibleAssets"), Nullable] public decimal? NetTangibleAssets { get; set; } // decimal(38, 0)
        [Column("totalStockholderEquity"), Nullable] public decimal? TotalStockholderEquity { get; set; } // decimal(38, 0)
        [Column("commonStock"), Nullable] public decimal? CommonStock { get; set; } // decimal(38, 0)
        [Column("otherStockholderEquity"), Nullable] public decimal? OtherStockholderEquity { get; set; } // decimal(38, 0)
        [Column("treasuryStock"), Nullable] public decimal? TreasuryStock { get; set; } // decimal(38, 0)
    }

    [Table(Schema = "dbo", Name = "CashFlowQuarterly")]
    public partial class CashFlowQuarterly
    {
        [Column(), PrimaryKey(1), NotNull] public int SecurityID { get; set; } // int
        [Column(), PrimaryKey(2), NotNull] public int Year { get; set; } // int
        [Column(), PrimaryKey(3), NotNull] public int Quarter { get; set; } // int
        [Column("endDate"), NotNull] public DateTime EndDate { get; set; } // date
        [Column("investments"), Nullable] public decimal? Investments { get; set; } // numeric(38, 0)
        [Column("netBorrowings"), Nullable] public decimal? NetBorrowings { get; set; } // numeric(38, 0)
        [Column("netIncome"), Nullable] public decimal? NetIncome { get; set; } // numeric(38, 0)
        [Column("issuanceOfStock"), Nullable] public decimal? IssuanceOfStock { get; set; } // numeric(38, 0)
        [Column("repurchaseOfStock"), Nullable] public decimal? RepurchaseOfStock { get; set; } // numeric(38, 0)
        [Column("effectOfExchangeRate"), Nullable] public decimal? EffectOfExchangeRate { get; set; } // numeric(38, 0)
        [Column("depreciation"), Nullable] public decimal? Depreciation { get; set; } // numeric(38, 0)
        [Column("dividendsPaid"), Nullable] public decimal? DividendsPaid { get; set; } // numeric(38, 0)
        [Column("changeInCash"), Nullable] public decimal? ChangeInCash { get; set; } // numeric(38, 0)
        [Column("changeToLiabilities"), Nullable] public decimal? ChangeToLiabilities { get; set; } // numeric(38, 0)
        [Column("changeToOperatingActivities"), Nullable] public decimal? ChangeToOperatingActivities { get; set; } // numeric(38, 0)
        [Column("changeToInventory"), Nullable] public decimal? ChangeToInventory { get; set; } // numeric(38, 0)
        [Column("changeToAccountReceivables"), Nullable] public decimal? ChangeToAccountReceivables { get; set; } // numeric(38, 0)
        [Column("otherCashflowsFromInvestingActivities"), Nullable] public decimal? OtherCashflowsFromInvestingActivities { get; set; } // numeric(38, 0)
        [Column("otherCashflowsFromFinancingActivities"), Nullable] public decimal? OtherCashflowsFromFinancingActivities { get; set; } // numeric(38, 0)
        [Column("totalCashflowsFromInvestingActivities"), Nullable] public decimal? TotalCashflowsFromInvestingActivities { get; set; } // numeric(38, 0)
        [Column("totalCashFromFinancingActivities"), Nullable] public decimal? TotalCashFromFinancingActivities { get; set; } // numeric(38, 0)
        [Column("totalCashFromOperatingActivities"), Nullable] public decimal? TotalCashFromOperatingActivities { get; set; } // numeric(38, 0)
        [Column("capitalExpenditures"), Nullable] public decimal? CapitalExpenditures { get; set; } // numeric(38, 0)
    }

    [Table(Schema = "dbo", Name = "IncomeStatementQuarterly")]
    public partial class IncomeStatementQuarterly
    {
        [Column(), PrimaryKey(1), NotNull] public int SecurityID { get; set; } // int
        [Column(), PrimaryKey(2), NotNull] public int Year { get; set; } // int
        [Column(), PrimaryKey(3), NotNull] public int Quarter { get; set; } // int
        [Column("endDate"), NotNull] public DateTime EndDate { get; set; } // date
        [Column("totalRevenue"), Nullable] public decimal? TotalRevenue { get; set; } // numeric(38, 0)
        [Column("costOfRevenue"), Nullable] public decimal? CostOfRevenue { get; set; } // numeric(38, 0)
        [Column("researchDevelopment"), Nullable] public decimal? ResearchDevelopment { get; set; } // numeric(38, 0)
        [Column("totalOperatingExpenses"), Nullable] public decimal? TotalOperatingExpenses { get; set; } // numeric(38, 0)
        [Column("totalOtherIncomeExpenseNet"), Nullable] public decimal? TotalOtherIncomeExpenseNet { get; set; } // numeric(38, 0)
        [Column("otherOperatingExpenses"), Nullable] public decimal? OtherOperatingExpenses { get; set; } // numeric(38, 0)
        [Column("minorityInterest"), Nullable] public decimal? MinorityInterest { get; set; } // numeric(38, 0)
        [Column("interestExpense"), Nullable] public decimal? InterestExpense { get; set; } // numeric(38, 0)
        [Column("extraordinaryItems"), Nullable] public decimal? ExtraordinaryItems { get; set; } // numeric(38, 0)
        [Column("sellingGeneralAdministrative"), Nullable] public decimal? SellingGeneralAdministrative { get; set; } // numeric(38, 0)
        [Column("nonRecurring"), Nullable] public decimal? NonRecurring { get; set; } // numeric(38, 0)
        [Column("otherItems"), Nullable] public decimal? OtherItems { get; set; } // numeric(38, 0)
        [Column("incomeTaxExpense"), Nullable] public decimal? IncomeTaxExpense { get; set; } // numeric(38, 0)
        [Column("netIncomeFromContinuingOps"), Nullable] public decimal? NetIncomeFromContinuingOps { get; set; } // numeric(38, 0)
        [Column("netIncomeApplicableToCommonShares"), Nullable] public decimal? NetIncomeApplicableToCommonShares { get; set; } // numeric(38, 0)
        [Column("discontinuedOperations"), Nullable] public decimal? DiscontinuedOperations { get; set; } // numeric(38, 0)
        [Column("effectOfAccountingCharges"), Nullable] public decimal? EffectOfAccountingCharges { get; set; } // numeric(38, 0)
        [Column("incomeBeforeTax"), Nullable] public decimal? IncomeBeforeTax { get; set; } // numeric(38, 0)
        [Column("ebit"), Nullable] public decimal? Ebit { get; set; } // numeric(38, 0)
        [Column("operatingIncome"), Nullable] public decimal? OperatingIncome { get; set; } // numeric(38, 0)
        [Column("netIncome"), Nullable] public decimal? NetIncome { get; set; } // numeric(38, 0)
        [Column("grossProfit"), Nullable] public decimal? GrossProfit { get; set; } // numeric(38, 0)
    }

    [Table(Schema = "dbo", Name = "Industry")]
    public partial class Industry
    {
        [Column(), PrimaryKey, Identity] public int IndustryID { get; set; } // int
        [Column(), NotNull] public int SectorID { get; set; } // int
        [Column("Industry"), NotNull] public string IndustryColumn { get; set; } // nvarchar(200)
    }

    [Table(Schema = "dbo", Name = "KeyRatio")]
    public partial class KeyRatio
    {
        [PrimaryKey(1), NotNull] public int SecurityID { get; set; } // int
        [PrimaryKey(2), NotNull] public int Year { get; set; } // int
        [PrimaryKey(3), NotNull] public int Quarter { get; set; } // int
        [Column, Nullable] public decimal? MarketCap { get; set; } // numeric(38, 6)
        [Column, Nullable] public decimal? Dividend { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? ROA { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? ROE { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? ROI { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? CurrentRatio { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? QuickRatio { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? LongTermDebtToEquity { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? DebtToEquity { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? GrossMargin { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? OperationMargin { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? ProfitMargin { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? Earnings { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? Price { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? Change { get; set; } // numeric(18, 6)
        [Column, Nullable] public decimal? Volume { get; set; } // numeric(38, 6)
    }

    [Table(Schema = "dbo", Name = "Sector")]
    public partial class Sector
    {
        [Column(), PrimaryKey, Identity] public int SectorID { get; set; } // int
        [Column("Sector"), Nullable] public string SectorColumn { get; set; } // nvarchar(200)
    }

    [Table(Schema = "dbo", Name = "Security")]
    public partial class Security
    {
        [PrimaryKey, Identity] public int SecurityID { get; set; } // int
        [Column, NotNull] public int SectorID { get; set; } // int
        [Column, NotNull] public int IndustryID { get; set; } // int
        [Column, NotNull] public string Ticker { get; set; } // nvarchar(6)
        [Column, NotNull] public string Company { get; set; } // nvarchar(200)
        [Column, NotNull] public string Country { get; set; } // nvarchar(50)
    }

    [Table(Schema = "dbo", Name = "TimeDimmension")]
    public partial class TimeDimmension
    {
        [PrimaryKey, NotNull] public int TimeID { get; set; } // int
        [Column, NotNull] public int Year { get; set; } // int
        [Column, NotNull] public int Quarter { get; set; } // int
    }

    public static partial class TableExtensions
    {
        public static BalanceSheetQuarterly Find(this ITable<BalanceSheetQuarterly> table, int SecurityID, int Year, int Quarter)
        {
            return table.FirstOrDefault(t =>
                t.SecurityID == SecurityID &&
                t.Year == Year &&
                t.Quarter == Quarter);
        }

        public static CashFlowQuarterly Find(this ITable<CashFlowQuarterly> table, int SecurityID, int Year, int Quarter)
        {
            return table.FirstOrDefault(t =>
                t.SecurityID == SecurityID &&
                t.Year == Year &&
                t.Quarter == Quarter);
        }

        public static IncomeStatementQuarterly Find(this ITable<IncomeStatementQuarterly> table, int SecurityID, int Year, int Quarter)
        {
            return table.FirstOrDefault(t =>
                t.SecurityID == SecurityID &&
                t.Year == Year &&
                t.Quarter == Quarter);
        }

        public static Industry Find(this ITable<Industry> table, int IndustryID)
        {
            return table.FirstOrDefault(t =>
                t.IndustryID == IndustryID);
        }

        public static KeyRatio Find(this ITable<KeyRatio> table, int SecurityID, int Year, int Quarter)
        {
            return table.FirstOrDefault(t =>
                t.SecurityID == SecurityID &&
                t.Year == Year &&
                t.Quarter == Quarter);
        }

        public static Sector Find(this ITable<Sector> table, int SectorID)
        {
            return table.FirstOrDefault(t =>
                t.SectorID == SectorID);
        }

        public static Security Find(this ITable<Security> table, int SecurityID)
        {
            return table.FirstOrDefault(t =>
                t.SecurityID == SecurityID);
        }

        public static TimeDimmension Find(this ITable<TimeDimmension> table, int TimeID)
        {
            return table.FirstOrDefault(t =>
                t.TimeID == TimeID);
        }
    }
}

#pragma warning restore 1591